steps:
  # Build images by Cloud Build
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/sdns-prd-273508/cloudruntest:$COMMIT_SHA'
      - '.'
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/sdns-prd-273508/cloudruntest:$COMMIT_SHA'
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cloudruntest'
      - '--image'
      - 'gcr.io/sdns-prd-273508/cloudruntest:$COMMIT_SHA'
      - '--region'
      - 'asia-southeast1'
      - '--platform'
      - 'managed'
images:
  - 'gcr.io/sdns-prd-273508/cloudruntest:$COMMIT_SHA'
